input_folder: ./sounds/input/
output_folder: ./sounds/output/
sample_rate: 22050
bandwidths:
  - 2000
  - 3000
  - 4000
  - 5000
  - 6000
  - 7000
  - 8000
  - 9000
  - 10000
normalisation: True
target: -25
